FROM node:16.18.1-slim AS builder
WORKDIR /root/app
COPY . .
RUN yarn install --frozen-lockfile && yarn cache clean
RUN yarn run build

FROM node:16.18.1-slim AS production
WORKDIR /root/app
COPY package.json yarn.lock /root/app/
RUN yarn install --production --frozen-lockfile && yarn cache clean
COPY --from=builder /root/app/dist /root/app/dist
COPY views /root/app/views
VOLUME /root/app/.env
EXPOSE 3000
CMD [ "yarn", "run", "start:dist" ]
