apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
nameSuffix: -main
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: food-map-server
  - path: service-patch.yaml
    target:
      kind: Service
      name: food-map-server
images:
  - name: food-map-server
    newTag: main-latest
