apiVersion: v1
kind: Service
metadata:
  name: food-map-server
  labels:
    app: food-map-server
spec:
  type: ClusterIP
  selector:
    app: food-map-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
